spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: Phaixann@121
#jpa Settings
  jpa.hibernate.ddl_auto: create


management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "caches"
      base_path: "/management-dashboard"
  endpoint:
    health:
      show-details: always